### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by acd62081** [cescobarresi/ciscoreputation#2]
Hello,
My Operating system is Ubuntu 16.04. I am getting a ValueError: No JSON object could be decoded when running ciscoreputation.py. I am not sure where to look next. Thank you for your help!

**The command that I am using for testing is:**
ciscoreputation 8.8.8.8 --tos

**The error occurs on the ciscoreputation.py line:** 
data = get_data(arguments['<query>'])

**The complete error message is:**

Traceback (most recent call last):
  File "ciscoreputation.py", line 142, in <module>
    do_main()
  File "ciscoreputation.py", line 95, in do_main
    data = get_data(arguments['<query>'])
  File "ciscoreputation.py", line 42, in get_data
    'query_entry':search_string
  File "/home/mal/.local/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by cescobarresi** [comment]
Hi, 
talosintelligence.com now requires to have the right REFERER HEADER.
Version v2.0.1 works correctly. Please update to latest release.

PS: 'email score' now has the same value as 'email reputation'. I'll look in to this in the future.
