### ISSUE TITLE
Error in ciscoreputation script

### ISSUE THREAD

**Issue by fredericpougnault** [cescobarresi/ciscoreputation#5]
Hello,

Since one week, when I execute ciscoreputation script I have this error

Traceback (most recent call last):
  File "/usr/bin/ciscoreputation", line 9, in <module>
    load_entry_point('ciscoreputation==2.0.1', 'console_scripts', 'ciscoreputation')()
  File "/usr/lib/python2.6/site-packages/ciscoreputation/__init__.py", line 4, in main
    do_main()
  File "/usr/lib/python2.6/site-packages/ciscoreputation/ciscoreputation.py", line 97, in do_main
    data = get_data(arguments['<query>'])
  File "/usr/lib/python2.6/site-packages/ciscoreputation/ciscoreputation.py", line 43, in get_data
    'query_entry':search_string
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib64/python2.6/site-packages/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/site-packages/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/site-packages/simplejson/decoder.py", line 353, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by paagalladka** [comment]
Hello @fredericpougnault,

Just replace 
headers={'referer':'https://talosintelligence.com/reputation_center/lookup?search=%s'%search_string}
with 
headers={'referer':'https://talosintelligence.com/reputation_center/lookup?search=%s'%search_string, 'User-agent': 'Mozilla/5.0'}

in ciscoreputation.py.

@cescobarresi : Can u please update the source to have a userAgent info.
Thanks

**Comment by fredericpougnault** [comment]
Hello @paagalladka,

Thank you for your response its works.

Regards,

**Comment by cescobarresi** [comment]
Thanks @fredericpougnault for pointing out the error and thanks to @paagalladka for supplying a useful answer.
I just fixed this issue. While I was there I though to simply rewrite the `print` statements to be compatible with python3.

Version v2.1.4 is [available at PyPi](https://pypi.org/project/ciscoreputation/)
