### ISSUE TITLE
ciscoreputation 2.1.4 - error JSONDecodeError

### ISSUE THREAD

**Issue by lcn0** [cescobarresi/ciscoreputation#8]
ciscoreputation reputation IP --tos
ciscoreputation 2.1.4
Traceback (most recent call last):
  File "/usr/local/bin/ciscoreputation", line 11, in <module>
    load_entry_point('ciscoreputation==2.1.4', 'console_scripts', 'ciscoreputation')()
  File "/usr/local/lib/python2.7/dist-packages/ciscoreputation-2.1.4-py2.7.egg/ciscoreputation/__init__.py", line 4, in main
    do_main()
  File "/usr/local/lib/python2.7/dist-packages/ciscoreputation-2.1.4-py2.7.egg/ciscoreputation/ciscoreputation.py", line 120, in do_main
    data = get_data(arguments['<query>'])
  File "/usr/local/lib/python2.7/dist-packages/ciscoreputation-2.1.4-py2.7.egg/ciscoreputation/ciscoreputation.py", line 46, in get_data
    'query_entry':search_string
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by erionsina** [comment]
I'm having this issue too with version 2.1.4

**Comment by pkeller** [comment]
This may be because Cisco now asks for a Captcha for non-logged in accounts. You can dump the HTML by doing `print(r_details.text)` and load this into a browser to see more-or-less what is going on. It is free to create a Cisco account, perhaps there is some way for account holders to bypass the Captcha (with an API key or some such mechanism)?

I would attach an example, but I can't get GitHub to accept the file (even as a .txt, .zip or .gz)
