### ISSUE TITLE
CANNOT IMPORT DO_MAIN

### ISSUE THREAD

**Issue by mantemp** [cescobarresi/ciscoreputation#9]
Traceback (most recent call last):
  File "/usr/local/bin/ciscoreputation", line 7, in <module>
    from ciscoreputation import main
  File "/usr/local/lib/python3.5/dist-packages/ciscoreputation/__init__.py", line 1, in <module>
    from ciscoreputation import do_main
ImportError: cannot import name 'do_main'

**Comment by lyghtkruz** [comment]
> Traceback (most recent call last):
> File "/usr/local/bin/ciscoreputation", line 7, in
> from ciscoreputation import main
> File "/usr/local/lib/python3.5/dist-packages/ciscoreputation/**init**.py", line 1, in
> from ciscoreputation import do_main
> ImportError: cannot import name 'do_main'

For whatever reason the virtualenv isn't picking up the package in site-packages.  If you go cd to lib/python3.5/ and: 
ln -s site-packages/ciscoreputation/ciscoreputation.py ./
ln -s site-packages/ciscoreputation/__about__.py ./

There's then errors about "main" not being able to be imported in bin/ciscoreputation

I was able to clear up that error by changing main to do_main but the code still fails for me trying to query anything.
